language: generic

os: osx
osx_image: xcode9.4

matrix:
  include:
  - name: "Python 2.7 Test"
    env: PYTHON=python2
  - name: "Python 3.6 Test"
    env: PYTHON=python3

addons:
  homebrew:
    packages:
    - gdal2
    - cmake
    - boost
    - tcl-tk

install:
    - ${PYTHON} -m pip install virtualenv
    - ${PYTHON} -m virtualenv env --system-site-packages
    - source env/bin/activate
    - ${PYTHON} -m pip install --upgrade --force-reinstall numpy
    - ${PYTHON} -m pip install scipy
    - if [ "${PYTHON}" == "python2" ]; then ${PYTHON} -m pip install mock; fi;
    - git clone https://thompsonsed@bitbucket.org/thompsonsed/pycoalescence.git
    - cd pycoalescence
    - git checkout develop
    - cd pycoalescence/lib
    - rm -rf necsim
    - git clone https://thompsonsed@bitbucket.org/thompsonsed/necsim.git
    - cd ../../../

script:
    - cd pycoalescence
    - ${PYTHON} setup.py install
    - cd pycoalescence/tests
    - export quick_test="True"
    - export bypass_gdal_warp="True"
    - $PYTHON} -m unittest test_coalescence_tree.py
    - $PYTHON} -m unittest test_dispersal_simulation.py
    - $PYTHON} -m unittest test_fragment_config.py
    - $PYTHON} -m unittest test_fragments.py
    - $PYTHON} -m unittest test_helper.py
    - $PYTHON} -m unittest test_install.py
    - $PYTHON} -m unittest test_landscape.py
    - $PYTHON} -m unittest test_landscape_metrics.py
    - $PYTHON} -m unittest test_map.py
    - $PYTHON} -m unittest test_merger.py
    - $PYTHON} -m unittest test_patched_landscape.py
    - $PYTHON} -m unittest test_pause_resume.py
    - $PYTHON} -m unittest test_simulation.py
    - $PYTHON} -m unittest test_spatial_algorithms.py
    - $PYTHON} -m unittest test_sqlite_connection.py
    - $PYTHON} -m unittest test_system.py
    - $PYTHON} -m unittest test_system_operations.py
#    - ${PYTHON} test_install.py --quick --bypass_gdal_warp TODO consider reverting to this method
    - echo "tests complete"
