language: generic

os: osx
osx_image: xcode9.2

python:
  - 2.7
  - 3.6

addons:
  homebrew:
    packages:
    - gdal
    - cmake
    - boost
    - valgrind

install:
    - git clone https://thompsonsed@bitbucket.org/thompsonsed/pycoalescence.git
    - cd pycoalescence/pycoalescence/lib
    - rm -rf necsim
    - git clone https://thompsonsed@bitbucket.org/thompsonsed/necsim.git
    - cd ../../../

script:
  - cd pycoalescence
  - python setup.py install
  - cd pycoalescence/tests
  - valgrind --track-origins=yes python testing_script.py
  - python test_install.py --quick -v
