language: generic

os: osx
osx_image: xcode9.4

env:
  matrix:
    - PYTHON_VER=2.7
    - PYTHON_VER=3.6

before_install:
    - brew install gdal
    - brew install cmake
    - brew install boost
    - brew install python==${PYTHON_VER}

install:
    -
      git clone https://thompsonsed@bitbucket.org/thompsonsed/pycoalescence.git
      cd pycoalescence/pycoalescence/lib
      rm -rf necsim
      git clone https://thompsonsed@bitbucket.org/thompsonsed/necsim.git
      cd ../../../

script:
  - cd pycoalescence
  - python setup.py install
  - cd pycoalescence/tests
  - python test_install.py --quick
