os: osx

addons:
  homebrew:
    packages:
    - md5sha1sum
  apt:
    - conda

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install -y conda-build 
  - git clone https://github.com/thompsonsed/pycoalescence-feedstock.git
  - mkdir pycoalescence
  - cp pycoalescence-feedstock/recipe/* pycoalescence
  - conda-build -y pycoalescence --no-test
  - conda install -y --use-local pycoalescence

script:
  - cd pycoalescence
  - python run_test.py
