os: osx


install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
  - bash ~/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install -y conda-build 
  - git clone https://github.com/thompsonsed/pycoalescence-feedstock.git
  - mkdir pycoalescence
  - cp pycoalescence-feedstock/recipe/* pycoalescence
  - conda-build -y pycoalescence
  - conda install -y --use-local pycoalescence

script:
  - cd pycoalescence
  - python run_test.py
