language: generic

os: osx
osx_image: xcode9.2

python:
  - 2.7
  - 3.6

addons:
  homebrew:
    packages:
    - gdal
    - cmake
    - boost
    - valgrind

install:
    - python -m virtualenv env
    - source env/bin/activate
    - python -m pip install numpy scipy >=0.12.0
    - git clone https://thompsonsed@bitbucket.org/thompsonsed/pycoalescence.git
    - cd pycoalescence/pycoalescence/lib
    - rm -rf necsim
    - git clone https://thompsonsed@bitbucket.org/thompsonsed/necsim.git
    - cd ../../../

script:
  - cd pycoalescence
  - python setup.py install
  - cd ..
  - valgrind --track-origins=yes --suppressions=valgrind-python.supp python -E -tt testing_script.py
  - cd pycoalescence/tests
  - python test_install.py --quick -v
