#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015


# scripts that run after cloning repository
install:
  # Download and copy the pycoalescence recipe to the correct place
  - cmd: git clone https://github.com/thompsonsed/pycoalescence-feedstock.git
  - cmd: mkdir pycoalescence
  - cmd: xcopy pycoalescence-feedstock\recipe pycoalescence
  # This part is taken from the conda.exe-forge appveyor.yml template
  # Cywing's git breaks conda.exe-build. (See https://github.com/conda.exe-forge/conda.exe-smithy-feedstock/pull/2.)
  - cmd: rmdir C:\cygwin /s /q

  # Add path, activate `conda.exe` and update conda.exe.
  - cmd: "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%" 
  - cmd: conda.exe config --set always_yes yes --set changeps1 no
  - cmd: conda.exe update --yes --quiet conda.exe

  - cmd: set PYTHONUNBUFFERED=1

  # Add our channels.
  - cmd: conda.exe config --set show_channel_urls true
  - cmd: conda.exe config --remove channels defaults
  - cmd: conda.exe config --add channels defaults
  - cmd: conda.exe config --add channels conda.exe-forge
  - cmd: conda.exe install conda.exe-build
  - cmd: conda.exe-build pycoalescence

test_script:
  # Run some basic tests to ensure it installs
  - cmd: conda.exe install --use-local pycoalescence
  - cmd: cd pycoalescence
  - cmd: python.exe run_test.py