#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015


shallow_clone: true
  
# Taken from https://github.com/Anaconda-Platform/anaconda-project/blob/master/appveyor.yml
environment:
  access_token:
    secure: p9gL1bQlyiAs68znCLDraCQsp7LCjNsaSu52rRh2o+2tua8dEr9hv2v506X1zhXz
  
  global:
    PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                      # of 32 bit and 64 bit builds are needed, move this
                      # to the matrix section.
  matrix:

      - PYTHON: "C:\\Python35_64"
        PYTHON_VERSION: "3.5"
        BASE_PYTHON_VERSION: "3"
        PYTHON_ARCH: "64"
        CONDA_PY: "35"
        CONDA_NPY: "18"
      
      - PYTHON: "C:\\Python36_64"
        PYTHON_VERSION: "3.6"
        BASE_PYTHON_VERSION: "3"
        PYTHON_ARCH: "64"
        CONDA_PY: "36"
        CONDA_NPY: "18"

platform:
  -x64

# scripts that run after cloning repository
install:
  # - cmd: powershell .\\install.ps1  #
  # - cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # These are already installed on appveyor.  Update them.
  - cmd: set CONDA_ROOT="C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
  - cmd: set PATH=""%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
  - cmd: echo CONDA_PREFIX %CONDA_PREFIX%
  - cmd: echo CONDA_ROOT %CONDA_ROOT%
  - cmd: echo PATH %PATH%
  # Add path, activate `conda` and update conda.
  - cmd: "%CONDA_ROOT%\\Scripts\\activate root"
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update --yes --quiet conda
  # Download and copy the pycoalescence recipe to the correct place
  - cmd: git clone https://$($env:access_token)@github.com/thompsonsed/pycoalescence-feedstock.git
  - cmd: mkdir pycoalescence
  - cmd: xcopy pycoalescence-feedstock\recipe pycoalescence
  - cmd: set PYTHONUNBUFFERED=1
  # Add our channels.
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --remove channels defaults
  - cmd: conda config --add channels defaults
  - cmd: conda config --add channels conda-forge
  - cmd: conda install conda-build

# Custom build script
build_script:
  # Add path, activate `conda` and update conda.
  - cmd: "%CONDA_ROOT%\\Scripts\\activate root"
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update --yes --quiet conda
  - cmd: conda-build pycoalescence --no-test

test_script:
  - cmd: "%CONDA_ROOT%\\Scripts\\activate root"
  - cmd: conda config --set always_yes yes --set changeps1 no
  # Run some basic tests to ensure it installs
  - cmd: conda install --use-local pycoalescence
  - cmd: cd pycoalescence
  - cmd: python.exe run_test.py