#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015


shallow_clone: true
  
# Taken from https://github.com/Anaconda-Platform/anaconda-project/blob/master/appveyor.yml
environment:
  access_token:
    secure: p9gL1bQlyiAs68znCLDraCQsp7LCjNsaSu52rRh2o+2tua8dEr9hv2v506X1zhXz
  
  matrix:
    - CONFIG: win_c_compilervs2015cxx_compilervs2015python3.5vc14
      CONDA_INSTALL_LOCN: C:\Miniconda36-x64

    - CONFIG: win_c_compilervs2015cxx_compilervs2015python3.6vc14
      CONDA_INSTALL_LOCN: C:\Miniconda36-x64

platform:
  - x64

# Install process derived from https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/appveyor.yml
install:
    # Cywing's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
    - cmd: rmdir C:\cygwin /s /q
    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda.exe update --yes --quiet conda
    - cmd: set PYTHONUNBUFFERED=1
    # Add our channels.
    - cmd: conda.exe config --set show_channel_urls true
    - cmd: conda.exe config --remove channels defaults
    - cmd: conda.exe config --add channels defaults
    - cmd: conda.exe config --add channels conda-forge
    - cmd: conda.exe install conda-build -y --quiet
    # Download and copy the pycoalescence recipe to the correct place
    - cmd: git clone https://$($env:access_token)@github.com/thompsonsed/pycoalescence-feedstock.git
    - cmd: mkdir pycoalescence
    - cmd: xcopy pycoalescence-feedstock\recipe pycoalescence

# Skip .NET project specific build phase.
build: off

test_script:
  # Build and install pycoalescence, then run the basic tests
  - cmd: conda.exe build pycoalescence --quiet
  - cmd: conda.exe install --use-local -y pycoalescence
  - cmd: cd pycoalescence
  # Run basic tests
  - cmd: python.exe run_test.py
  # Pull the dev build of the package for running tests
  - cmd: git clone https://thompsonsed@bitbucket.org/thompsonsed/pycoalescence.git
  - cmd: cd pycoalescence
  - cmd: git checkout develop
  - cmd: cd pycoalescence/tests
  # Run full (short) tests
  - cmd: python.exe test_install.py --quick --bypass_gdal_warp